### ISSUE TITLE
geoclue

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1504]
New Linux only prefs:

https://bugzilla.mozilla.org/show_bug.cgi?id=1063572

```js
pref("geo.provider.geoclue.always_high_accuracy", true);
pref("geo.provider.use_geoclue", true);
```

```yaml
# Whether to use Geoclue location provider (if available on the system).
- name: geo.provider.use_geoclue
  type: bool
  value: true
  mirror: always

# Whether to always provide high location accuracy, even if site
# doesn't actually request this level of accuracy.
# Almost no site correctly requests high accuracy so force it by default
# for compatibility with other geolocation providers.
- name: geo.provider.geoclue.always_high_accuracy
  type: bool
  value: true
  mirror: always
```

`geo.provider.use_geoclue=false` is worth considering for `0202` IMO.

_Originally posted by @rusty-snake in https://github.com/arkenfox/user.js/issues/1490#issuecomment-1183549133_
