### ISSUE TITLE
-moz font property FP test

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1509]
STR
- go to https://arkenfox.github.io/TZP/tzp.html#theend
- click on the `show perf & debugging`
- copypaste the `sys fonts` results and state OS + version

Looking to see if I can reduce the test to three items in FF, instead of 16 (and save 2.5ms)

Also looking to see if the first 12 items differ per OS version (esp windows, probably linux desktop environments and/or distros)

TIA ❤️ 

here's windows 7 (and android)
```
FF52-103: windows 7: 6a6aa704622165913da4e2985dacbcd73b8ff466 
- doesn't change with TB
- doesn't change with language AFAICT
- doesn't change with zoom
- [ui] doesn't change with default zoom (all: i.e not zoom text only)

"caption:               Segoe UI 12px" (Roboto 12px)
"icon:                  Segoe UI 12px"
"menu:                  Segoe UI 12px"
"message-box:           Segoe UI 12px"
"small-caption:         Segoe UI 12px"
"status-bar:            Segoe UI 12px"
"-moz-window:           Segoe UI 12px"
"-moz-desktop:          Segoe UI 12px"
"-moz-document:         Segoe UI 12px"
"-moz-workspace:        Segoe UI 12px"
"-moz-info:             Segoe UI 12px"
"-moz-pull-down-menu:   Segoe UI 12px"

"-moz-dialog:           MS Shell Dlg \\32  12px" (Roboto 12px)

"-moz-button:           MS Shell Dlg \\32  13.3333px" (Roboto 13.3333px)
"-moz-list:             MS Shell Dlg \\32  13.3333px"
"-moz-field:            MS Shell Dlg \\32  13.3333px"
```

**Comment by fxbrit** [comment]
- macOS 12.4
- FF102, Nightly104, TB11.5 (91.11.0esr)
```
  "caption:             -apple-system 13px",
  "icon:                -apple-system 12px",
  "menu:                -apple-system 13px",
  "message-box:         -apple-system 11px",
  "small-caption:       -apple-system 11px",
  "status-bar:          -apple-system 11px",
  "-moz-window:         sans-serif 14px",
  "-moz-desktop:        -apple-system 12px",
  "-moz-document:       sans-serif 14px",
  "-moz-workspace:      -apple-system 12px",
  "-moz-info:           -apple-system 12px",
  "-moz-pull-down-menu: -apple-system 13px",
  "-moz-dialog:         -apple-system 13px",
  "-moz-button:         -apple-system 13.3333px",
  "-moz-list:           -apple-system 13.3333px",
  "-moz-field:          -apple-system 13.3333px"
```

**Comment by Thorin-Oakenpants** [comment]
hey 🎣 ... what do you get if you go to settings > general and change default zoom to e.g. 133% _AND_ tick "zoom text only"

**Comment by fxbrit** [comment]
> 133% AND tick "zoom text only"

```yaml
- caption:              -apple-system 17.29px
- icon:                 -apple-system 15.96px
- menu:                 -apple-system 17.29px
- message-box:          -apple-system 14.63px
- small-caption:        -apple-system 14.63px
- status-bar:           -apple-system 14.63px
- -moz-window:          sans-serif 18.62px
- -moz-desktop:         -apple-system 15.96px
- -moz-document:        sans-serif 18.62px
- -moz-workspace:       -apple-system 15.96px
- -moz-info:            -apple-system 15.96px
- -moz-pull-down-menu:  -apple-system 17.29px
- -moz-dialog:          -apple-system 17.29px
- -moz-button:          -apple-system 17.7333px
- -moz-list:            -apple-system 17.7333px
- -moz-field:           -apple-system 17.7333px
```
