### ISSUE TITLE
Why is the letterbox colour white, and not dark, like in Mullvad and Tor?

### ISSUE THREAD

**Issue by GlitteringReturn** [arkenfox/user.js#1805]
Disclaimer: I have _zero_ knowledge in computer science, I am studying science.

You should have read the title, also why does the letter box have a margin on the top, this is also absent in Mullvad and Tor, it makes arkenfox a lot uglier. The next question is, is this necessary?

FYI: I have checked how to change this (https://github.com/arkenfox/user.js/issues/747), it didn't work, maybe this is a bug?

**Comment by crssi** [comment]
Open `about:config` and flip `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`

In your FF profile create folder named `chrome`

In that folder:
1. create a file named `userChrome.css` in paste in the following
``` css
/* letterbox color */
#tabbrowser-tabpanels {
  background-color: rgb(46,54,69) !important;
}
```

2. create a file named `userContent.css` in paste in the following
``` css
@-moz-document url("about:home"),url("about:blank"),url("about:newtab"),url("about:privatebrowsing") {
  body{ background-color: rgb(46,54,69) }
}
```

**Comment by Thorin-Oakenpants** [comment]
the reason is because the TB patches haven't been uplifted to Mozilla

**Comment by Thorin-Oakenpants** [comment]
@crssi - this is the entry I have: old notes, haven't touched it in a year or more: works fine
- i.e I never see about:blank or newtab because they are set to use a speed dial extension
- so the bit here is the letterboxing (vbox)
- i fucking hate css, so no questions, just posting for the shits and giggles

```css
/* about:newtab and about:blank: also colors the letterboxing
 * NOT needed: but I like to match speed dial */
/* dark theme is #2a2a2e = way too light */ 
#browser vbox#appcontent tabbrowser, #content, #tabbrowser-tabpanels,
browser[type=content-primary], browser[type=content] > html {
	background: #0f0f0f !important;
}
```
